Add [rocq makefile] support for installing packages.

diff --git a/tools/CoqMakefile.in b/tools/CoqMakefile.in
--- a/tools/CoqMakefile.in
+++ b/tools/CoqMakefile.in
@@ -27,15 +27,21 @@ MLGFILES          := $(COQMF_MLGFILES)
 MLPACKFILES       := $(COQMF_MLPACKFILES)
 MLLIBFILES        := $(COQMF_MLLIBFILES)
 METAFILE          := $(COQMF_METAFILE)
+ROCQPACKAGE       := $(COQMF_ROCQPACKAGE)
+LEGACYSUPPORT     := $(COQMF_LEGACY_SUPPORT)
+HASROCQPATH       := $(COQMF_HAS_ROCQPATH)
+ROCQPATH          := $(COQMF_ROCQPATH)
+COQMF_PACKAGEFLAGS = $(foreach pkg,$(COQMF_PACKAGES),-package $(pkg))
+COQMF_PACKAGEMLFLAGS = $(if $(COQMF_PACKAGES),$(shell $(ROCQFIND) -I $(COQMF_PACKAGES)))
 CMDLINE_VFILES    := $(COQMF_CMDLINE_VFILES)
 INSTALLCOQDOCROOT := $(COQMF_INSTALLCOQDOCROOT)
 OTHERFLAGS        := $(COQMF_OTHERFLAGS)
 COQCORE_SRC_SUBDIRS := $(COQMF_COQ_SRC_SUBDIRS)
-OCAMLLIBS         := $(COQMF_OCAMLLIBS)
+OCAMLLIBS          = $(COQMF_OCAMLLIBS) $(COQMF_PACKAGEMLFLAGS)
 SRC_SUBDIRS       := $(COQMF_SRC_SUBDIRS)
-COQLIBS           := $(COQMF_COQLIBS)
-COQLIBS_NOML      := $(COQMF_COQLIBS_NOML)
-CMDLINE_COQLIBS   := $(COQMF_CMDLINE_COQLIBS)
+COQLIBS            = $(COQMF_COQLIBS) $(COQMF_PACKAGEFLAGS)
+COQLIBS_NOML       = $(COQMF_COQLIBS_NOML) $(COQMF_PACKAGEFLAGS)
+CMDLINE_COQLIBS    = $(COQMF_CMDLINE_COQLIBS) $(COQMF_PACKAGEFLAGS)
 COQLIB            := $(COQMF_COQLIB)
 COQCORELIB        := $(COQMF_COQCORELIB)
 DOCDIR            := $(COQMF_DOCDIR)
@@ -103,6 +109,7 @@ COQDEP   ?= "$(COQBIN)rocq" dep
 COQDOC   ?= "$(COQBIN)rocq" doc
 COQPP    ?= "$(COQBIN)rocq" pp-mlg
 COQMKFILE ?= "$(COQBIN)rocq" makefile
+ROCQFIND ?= "$(COQBIN)rocqfind"
 OCAMLLIBDEP ?= "$(COQBIN)ocamllibdep"
 
 # Timing scripts
@@ -129,7 +136,7 @@ COQDEBUG ?=
 
 # Extra packages to be linked in (as in findlib -package)
 CAMLPKGS ?=
-FINDLIBPKGS = -package rocq-runtime.plugins.ltac $(CAMLPKGS)
+FINDLIBPKGS = -package rocq-runtime.plugins.ltac $(COQMF_PACKAGEFLAGS) $(CAMLPKGS)
 
 # Option for making timing files
 TIMING?=
@@ -172,6 +179,8 @@ COQTOPINSTALL ?= $(call destination_path,$(COQLIB)/toploop) # FIXME: Unused vari
 # findlib files installation
 FINDLIBPREINST= mkdir -p "$(COQPLUGININSTALL)/"
 FINDLIBDESTDIR= -destdir "$(COQPLUGININSTALL)/"
+FINDLIBPACKAGEINSTALL = $(COQPLUGININSTALL)/$(FINDLIBPACKAGE)
+FINDLIBROCQINSTALL = $(FINDLIBPACKAGEINSTALL)/rocq.d
 
 # we need to move out of sight $(METAFILE) otherwise findlib thinks the
 # package is already installed
@@ -186,6 +195,7 @@ findlib_install = \
 	fi
 findlib_remove = \
 	$(HIDE)if [ ! -z "$(METAFILE)" ]; then\
+	  if [ "$(ROCQPACKAGE)" ]; then rm -rf "$(FINDLIBROCQINSTALL)"; fi; \
 	  "$(OCAMLFIND)" remove $(FINDLIBDESTDIR) $(FINDLIBPACKAGE); \
 	fi
 
@@ -382,7 +392,7 @@ ALLNATIVEFILES = \
 	$(OBJFILES:.o=.cmi) \
 	$(OBJFILES:.o=.cmx) \
 	$(OBJFILES:.o=.cmxs)
-FINDLIBPACKAGE=$(patsubst .%,%,$(suffix $(METAFILE)))
+FINDLIBPACKAGE=$(if $(ROCQPACKAGE),$(ROCQPACKAGE),$(patsubst .%,%,$(suffix $(METAFILE))))
 
 # trick: wildcard filters out non-existing files, so that `install` doesn't show
 # warnings and `clean` doesn't pass to rm a list of files that is too long for
@@ -581,18 +591,51 @@ install: META
 	$(HIDE)code=0; for f in $$(cat .filestoinstall); do\
 	 if ! [ -f "$$f" ]; then >&2 echo $$f does not exist; code=1; fi \
 	done; exit $$code
-	$(HIDE)for f in $$(cat .filestoinstall); do\
-	 df="`$(COQMKFILE) -destination-of "$$f" $(COQLIBS)`";\
-	 if [ "$$?" != "0" -o -z "$$df" ]; then\
-	   echo SKIP "$$f" since it has no logical path;\
-	 else\
-	   install -d "$(COQLIBINSTALL)/$$df" &&\
-	   install -m 0644 "$$f" "$(COQLIBINSTALL)/$$df" &&\
-	   echo INSTALL "$$f" "$(COQLIBINSTALL)/$$df";\
-	 fi;\
-	done
 	$(call findlib_remove)
 	$(call findlib_install, META $(FINDLIBFILESTOINSTALL))
+	$(HIDE)if [ "$(ROCQPACKAGE)" ]; then \
+	 if [ "$(HASROCQPATH)" != "true" ]; then echo "Error: $(METAFILE) has no top-level rocqpath field"; exit 1; fi; \
+	 root="$(subst .,/,$(ROCQPATH))"; \
+	 for f in $$(cat .filestoinstall); do\
+	   df="`$(COQMKFILE) -destination-of "$$f" $(COQLIBS)`"; rc="$$?";\
+	   if [ "$$rc" != "0" -o -z "$$df" ]; then\
+	     echo SKIP "$$f" since it has no logical path;\
+	   else\
+	     if [ "$$df" = "''" ]; then df=""; fi; \
+	     rel="$$df"; \
+	     if [ -n "$$root" ]; then \
+	       case "$$df" in \
+	         "$$root") rel="" ;; \
+	         "$$root"/*) rel="$${df#$$root/}" ;; \
+	         *) echo SKIP "$$f" since it is outside rocqpath "$(ROCQPATH)"; continue ;; \
+	       esac; \
+	     else \
+	       case "$$rel" in /*) rel="$${rel#/}" ;; esac; \
+	     fi; \
+	     dest="$(FINDLIBROCQINSTALL)"; \
+	     if [ -n "$$rel" ]; then dest="$$dest/$$rel"; fi; \
+	     install -d "$$dest" &&\
+	     install -m 0644 "$$f" "$$dest" &&\
+	     echo INSTALL "$$f" "$$dest";\
+	     if [ "$(LEGACYSUPPORT)" = "true" ]; then \
+	       install -d "$(COQLIBINSTALL)/$$df" &&\
+	       install -m 0644 "$$f" "$(COQLIBINSTALL)/$$df" &&\
+	       echo INSTALL "$$f" "$(COQLIBINSTALL)/$$df";\
+	     fi; \
+	   fi;\
+	 done; \
+	else \
+	 for f in $$(cat .filestoinstall); do\
+	   df="`$(COQMKFILE) -destination-of "$$f" $(COQLIBS)`";\
+	   if [ "$$?" != "0" -o -z "$$df" ]; then\
+	     echo SKIP "$$f" since it has no logical path;\
+	   else\
+	     install -d "$(COQLIBINSTALL)/$$df" &&\
+	     install -m 0644 "$$f" "$(COQLIBINSTALL)/$$df" &&\
+	     echo INSTALL "$$f" "$(COQLIBINSTALL)/$$df";\
+	   fi;\
+	 done; \
+	fi
 	$(HIDE)$(MAKE) install-extra -f "$(SELF)"
 	@rm -f .filestoinstall
 install-extra::
@@ -601,7 +644,11 @@ install-extra::
 
 META: $(METAFILE)
 	$(HIDE)if [ "$(METAFILE)" ]; then \
-		cat "$(METAFILE)" | grep -v 'directory.*=.*' > META; \
+		if [ "$(ROCQPACKAGE)" ]; then \
+		  cp "$(METAFILE)" META; \
+		else \
+		  cat "$(METAFILE)" | grep -v 'directory.*=.*' > META; \
+		fi; \
 	fi
 
 install-byte:
@@ -628,17 +675,21 @@ uninstall::
 	@# Extension point
 	@$(MKFILESTOINSTALL)
 	$(call findlib_remove)
-	$(HIDE)for f in $$(cat .filestoinstall); do \
-	 df="`$(COQMKFILE) -destination-of "$$f" $(COQLIBS)`" &&\
-	 instf="$(COQLIBINSTALL)/$$df/`basename $$f`" &&\
-	 rm -f "$$instf" &&\
-	 echo RM "$$instf" ;\
-	done
-	$(HIDE)for f in $$(cat .filestoinstall); do \
-	 df="`$(COQMKFILE) -destination-of "$$f" $(COQLIBS)`" &&\
-	 echo RMDIR "$(COQLIBINSTALL)/$$df/" &&\
-	 (rmdir "$(COQLIBINSTALL)/$$df/" 2>/dev/null || true); \
-	done
+	$(HIDE)if [ -z "$(ROCQPACKAGE)" ] || [ "$(LEGACYSUPPORT)" = "true" ]; then \
+	 for f in $$(cat .filestoinstall); do \
+	   df="`$(COQMKFILE) -destination-of "$$f" $(COQLIBS)`" &&\
+	   if [ "$$df" = "''" ]; then df=""; fi; \
+	   instf="$(COQLIBINSTALL)/$$df/`basename $$f`" &&\
+	   rm -f "$$instf" &&\
+	   echo RM "$$instf" ;\
+	 done; \
+	 for f in $$(cat .filestoinstall); do \
+	   df="`$(COQMKFILE) -destination-of "$$f" $(COQLIBS)`" &&\
+	   if [ "$$df" = "''" ]; then df=""; fi; \
+	   echo RMDIR "$(COQLIBINSTALL)/$$df/" &&\
+	   (rmdir "$(COQLIBINSTALL)/$$df/" 2>/dev/null || true); \
+	 done; \
+	fi
 	@rm -f .filestoinstall
 
 .PHONY: uninstall
@@ -865,15 +916,15 @@ $(addsuffix .d,$(ALLSRCFILES)): $(GENMLFILES)
 
 $(addsuffix .d,$(MLIFILES)): %.mli.d: %.mli
 	$(SHOW)'CAMLDEP $<'
-	$(HIDE)$(CAMLDEP) $(OCAMLLIBS) "$<" $(redir_if_ok)
+	$(HIDE)$(CAMLDEP) $(OCAMLLIBS) $(COQMF_PACKAGEFLAGS) "$<" $(redir_if_ok)
 
 $(addsuffix .d,$(MLGFILES)): %.mlg.d: %.ml
 	$(SHOW)'CAMLDEP $<'
-	$(HIDE)$(CAMLDEP) $(OCAMLLIBS) "$<" $(redir_if_ok)
+	$(HIDE)$(CAMLDEP) $(OCAMLLIBS) $(COQMF_PACKAGEFLAGS) "$<" $(redir_if_ok)
 
 $(addsuffix .d,$(MLFILES)): %.ml.d: %.ml
 	$(SHOW)'CAMLDEP $<'
-	$(HIDE)$(CAMLDEP) $(OCAMLLIBS) "$<" $(redir_if_ok)
+	$(HIDE)$(CAMLDEP) $(OCAMLLIBS) $(COQMF_PACKAGEFLAGS) "$<" $(redir_if_ok)
 
 $(addsuffix .d,$(MLLIBFILES)): %.mllib.d: %.mllib
 	$(SHOW)'OCAMLLIBDEP $<'
